export const DINO_EVENT_INPUT_MANAGER: string = "DINO_EVENT_INPUT_MANAGER";
export const DINO_EVENT_FOOD_ATE: string = "DINO_EVENT_FOOD_ATE";
export const DINO_EVENT_FOOD_DESTROY: string = "DINO_EVENT_FOOD_DESTROY";
export const DINO_EVENT_CHARACTER_DEAD: string = "DINO_EVENT_CHARACTER_DEAD";